### ISSUE TITLE
Homebrew update location

### ISSUE THREAD

**Issue by washburnad** [FirehoseWeekend/install-guide#2]
I got this recommendation when running homebrew

$ ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
Whoops, the Homebrew installer has moved! Please instead run:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

Also, please ask wherever you got this link from to update it to the above.
Thanks!

**Comment by kenmazaika** [comment]
Thanks, Aaron.  We'll update the instructions soon!

**Comment by kenmazaika** [comment]
Thanks, Aaron.  I fixed that in this commit, https://github.com/FirehoseWeekend/install-guide/commit/120e5d2cb1dab8d66fa8a9f794e48f34fddf444c.
